#include "core/rendering/screen.hpp"

#include <SDL3/SDL.h>

#include <algorithm>  // Para max, min, transform
#include <cctype>     // Para toupper
#include <fstream>    // Para basic_ostream, operator<<, endl, basic_...
#include <iostream>   // Para cerr
#include <iterator>   // Para istreambuf_iterator, operator==
#include <string>     // Para char_traits, string, operator+, operator==

#include "core/input/mouse.hpp"                     // Para updateCursorVisibility
#include "core/rendering/opengl/opengl_shader.hpp"  // Para OpenGLShader
#include "core/rendering/surface.hpp"               // Para Surface, readPalFile
#include "core/rendering/text.hpp"                  // Para Text
#include "core/resources/resource_cache.hpp"        // Para Resource
#include "core/resources/resource_helper.hpp"       // Para ResourceHelper
#include "core/resources/resource_list.hpp"         // Para Asset, AssetType
#include "game/options.hpp"                         // Para Options, options, OptionsVideo, Border
#include "game/ui/notifier.hpp"                     // Para Notifier
#include "utils/color.hpp"                          // Para Color

// [SINGLETON]
Screen* Screen::screen = nullptr;

// [SINGLETON] Crearemos el objeto con esta función estática
void Screen::init() {
    Screen::screen = new Screen();
}

// [SINGLETON] Destruiremos el objeto con esta función estática
void Screen::destroy() {
    delete Screen::screen;
}

// [SINGLETON] Con este método obtenemos el objeto y podemos trabajar con él
auto Screen::get() -> Screen* {
    return Screen::screen;
}

// Constructor
Screen::Screen()
    : palettes_(Resource::List::get()->getListByType(Resource::List::Type::PALETTE)) {
    // Arranca SDL VIDEO, crea la ventana y el renderizador
    initSDLVideo();
    if (Options::video.fullscreen) {
        SDL_HideCursor();
    }

    // Ajusta los tamaños
    game_surface_dstrect_ = {.x = Options::video.border.width, .y = Options::video.border.height, .w = Options::game.width, .h = Options::game.height};
    // adjustWindowSize();
    current_palette_ = findPalette(Options::video.palette);

    // Define el color del borde para el modo de pantalla completa
    border_color_ = Color::index(Color::Cpc::BLACK);

    // Crea la textura donde se dibujan los graficos del juego
    game_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, Options::game.width, Options::game.height);
    if (game_texture_ == nullptr) {
        // Registrar el error si está habilitado
        if (Options::console) {
            std::cerr << "Error: game_texture_ could not be created!\nSDL Error: " << SDL_GetError() << '\n';
        }
    }
    SDL_SetTextureScaleMode(game_texture_, SDL_SCALEMODE_NEAREST);

    // Crea la textura donde se dibuja el borde que rodea el area de juego
    border_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, Options::game.width + (Options::video.border.width * 2), Options::game.height + (Options::video.border.height * 2));
    if (border_texture_ == nullptr) {
        // Registrar el error si está habilitado
        if (Options::console) {
            std::cerr << "Error: border_texture_ could not be created!\nSDL Error: " << SDL_GetError() << '\n';
        }
    }
    SDL_SetTextureScaleMode(border_texture_, SDL_SCALEMODE_NEAREST);

    // Cargar la paleta una sola vez
    auto initial_palette = readPalFile(palettes_.at(current_palette_));

    // Crea la surface donde se dibujan los graficos del juego
    game_surface_ = std::make_shared<Surface>(Options::game.width, Options::game.height);
    game_surface_->setPalette(initial_palette);
    game_surface_->clear(Color::index(Color::Cpc::BLACK));

    // Crea la surface para el borde de colores
    border_surface_ = std::make_shared<Surface>(Options::game.width + (Options::video.border.width * 2), Options::game.height + (Options::video.border.height * 2));
    border_surface_->setPalette(initial_palette);
    border_surface_->clear(border_color_);

    // Establece la surface que actuará como renderer para recibir las llamadas a render()
    renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(game_surface_);

    // Crea el objeto de texto para la pantalla de carga
    createText();

    // Extrae el nombre de las paletas desde su ruta
    processPaletteList();

    // Renderizar una vez la textura vacía para que tenga contenido válido
    // antes de inicializar los shaders (evita pantalla negra)
    SDL_RenderTexture(renderer_, game_texture_, nullptr, nullptr);
    SDL_RenderTexture(renderer_, border_texture_, nullptr, nullptr);

    // Ahora sí inicializar los shaders
    initShaders();
}

// Destructor
Screen::~Screen() {
    SDL_DestroyTexture(game_texture_);
    SDL_DestroyTexture(border_texture_);
}

// Limpia el renderer
void Screen::clearRenderer(ColorRGB color) {
    SDL_SetRenderDrawColor(renderer_, color.r, color.g, color.b, 0xFF);
    SDL_RenderClear(renderer_);
}

// Prepara para empezar a dibujar en la textura de juego
void Screen::start() { setRendererSurface(nullptr); }

// Vuelca el contenido del renderizador en pantalla
void Screen::render() {
    fps_.increment();

    // Renderiza todos los overlays
    renderOverlays();

    // Copia la surface a la textura
    surfaceToTexture();

    // Copia la textura al renderizador
    textureToRenderer();
}

// Establece el modo de video
void Screen::setVideoMode(bool mode) {
    // Actualiza las opciones
    Options::video.fullscreen = mode;

    // Configura el modo de pantalla y ajusta la ventana
    SDL_SetWindowFullscreen(window_, Options::video.fullscreen);
    adjustWindowSize();
    adjustRenderLogicalSize();
}

// Camibia entre pantalla completa y ventana
void Screen::toggleVideoMode() {
    Options::video.fullscreen = !Options::video.fullscreen;
    setVideoMode(Options::video.fullscreen);
}

// Reduce el tamaño de la ventana
auto Screen::decWindowZoom() -> bool {
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        const int PREVIOUS_ZOOM = Options::window.zoom;
        --Options::window.zoom;
        Options::window.zoom = std::max(Options::window.zoom, 1);

        if (Options::window.zoom != PREVIOUS_ZOOM) {
            setVideoMode(Options::video.fullscreen);
            return true;
        }
    }

    return false;
}

// Aumenta el tamaño de la ventana
auto Screen::incWindowZoom() -> bool {
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        const int PREVIOUS_ZOOM = Options::window.zoom;
        ++Options::window.zoom;
        Options::window.zoom = std::min(Options::window.zoom, Options::window.max_zoom);

        if (Options::window.zoom != PREVIOUS_ZOOM) {
            setVideoMode(Options::video.fullscreen);
            return true;
        }
    }

    return false;
}

// Cambia el color del borde
void Screen::setBorderColor(Uint8 color) {
    border_color_ = color;
    border_surface_->clear(border_color_);
}

// Cambia entre borde visible y no visible
void Screen::toggleBorder() {
    Options::video.border.enabled = !Options::video.border.enabled;
    setVideoMode(Options::video.fullscreen);
    initShaders();
}

// Dibuja las notificaciones
void Screen::renderNotifications() const {
    if (notifications_enabled_) {
        Notifier::get()->render();
    }
}

// Cambia el estado de los shaders
void Screen::toggleShaders() {
    Options::video.shaders = !Options::video.shaders;
    initShaders();
}

// Actualiza la lógica de la clase (versión nueva con delta_time para escenas migradas)
void Screen::update(float delta_time) {
    int old_fps = fps_.last_value;
    fps_.calculate(SDL_GetTicks());

    // Actualizar título de ventana si cambió el FPS
    if (fps_.last_value != old_fps) {
        std::string title = Options::window.caption + " - " + std::to_string(fps_.last_value) + " FPS";
        SDL_SetWindowTitle(window_, title.c_str());
    }

    Notifier::get()->update(delta_time);
    Mouse::updateCursorVisibility();
}

// Calcula el tamaño de la ventana
void Screen::adjustWindowSize() {
    window_width_ = Options::game.width + (Options::video.border.enabled ? Options::video.border.width * 2 : 0);
    window_height_ = Options::game.height + (Options::video.border.enabled ? Options::video.border.height * 2 : 0);

    // Establece el nuevo tamaño
    if (static_cast<int>(Options::video.fullscreen) == 0) {
        int old_width;
        int old_height;
        SDL_GetWindowSize(window_, &old_width, &old_height);

        int old_pos_x;
        int old_pos_y;
        SDL_GetWindowPosition(window_, &old_pos_x, &old_pos_y);

        const int NEW_POS_X = old_pos_x + ((old_width - (window_width_ * Options::window.zoom)) / 2);
        const int NEW_POS_Y = old_pos_y + ((old_height - (window_height_ * Options::window.zoom)) / 2);

        SDL_SetWindowSize(window_, window_width_ * Options::window.zoom, window_height_ * Options::window.zoom);
        SDL_SetWindowPosition(window_, std::max(NEW_POS_X, WINDOWS_DECORATIONS), std::max(NEW_POS_Y, 0));
    }
}

// Ajusta el tamaño lógico del renderizador
void Screen::adjustRenderLogicalSize() {
    SDL_SetRenderLogicalPresentation(renderer_, window_width_, window_height_, Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
}

// Establece el renderizador para las surfaces
void Screen::setRendererSurface(const std::shared_ptr<Surface>& surface) {
    (surface) ? renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(surface) : renderer_surface_ = std::make_shared<std::shared_ptr<Surface>>(game_surface_);
}

// Cambia la paleta
void Screen::nextPalette() {
    ++current_palette_;
    if (current_palette_ == static_cast<int>(palettes_.size())) {
        current_palette_ = 0;
    }

    setPalete();
}

// Cambia la paleta
void Screen::previousPalette() {
    if (current_palette_ > 0) {
        --current_palette_;
    } else {
        current_palette_ = static_cast<Uint8>(palettes_.size() - 1);
    }

    setPalete();
}

// Establece la paleta
void Screen::setPalete() {
    game_surface_->loadPalette(Resource::Cache::get()->getPalette(palettes_.at(current_palette_)));
    border_surface_->loadPalette(Resource::Cache::get()->getPalette(palettes_.at(current_palette_)));

    Options::video.palette = palettes_.at(current_palette_);

    // Eliminar ".gif"
    size_t pos = Options::video.palette.find(".pal");
    if (pos != std::string::npos) {
        Options::video.palette.erase(pos, 4);
    }

    // Convertir a mayúsculas
    std::ranges::transform(Options::video.palette, Options::video.palette.begin(), ::toupper);
}

// Extrae los nombres de las paletas
void Screen::processPaletteList() {
    for (auto& palette : palettes_) {
        palette = getFileName(palette);
    }
}

// Copia la surface a la textura
void Screen::surfaceToTexture() {
    if (Options::video.border.enabled) {
        border_surface_->copyToTexture(renderer_, border_texture_);
        game_surface_->copyToTexture(renderer_, border_texture_, nullptr, &game_surface_dstrect_);
    } else {
        game_surface_->copyToTexture(renderer_, game_texture_);
    }
}

// Copia la textura al renderizador
void Screen::textureToRenderer() {
    SDL_Texture* texture_to_render = Options::video.border.enabled ? border_texture_ : game_texture_;

    if (Options::video.shaders && shader_backend_) {
        shader_backend_->render();
    } else {
        SDL_SetRenderTarget(renderer_, nullptr);
        SDL_SetRenderDrawColor(renderer_, 0x00, 0x00, 0x00, 0xFF);
        SDL_RenderClear(renderer_);
        SDL_RenderTexture(renderer_, texture_to_render, nullptr, nullptr);
        SDL_RenderPresent(renderer_);
    }
}

// Renderiza todos los overlays
void Screen::renderOverlays() {
    renderNotifications();
#ifdef _DEBUG
    // renderInfo();
#endif
}

// Localiza la paleta dentro del vector de paletas
auto Screen::findPalette(const std::string& name) -> size_t {
    std::string upper_name = toUpper(name + ".pal");

    for (size_t i = 0; i < palettes_.size(); ++i) {
        if (toUpper(getFileName(palettes_[i])) == upper_name) {
            return i;
        }
    }
    return static_cast<size_t>(0);
}

// Muestra información por pantalla
void Screen::renderInfo() {
    if (show_debug_info_ && (Resource::Cache::get() != nullptr)) {
        auto text = Resource::Cache::get()->getText("smb2");
        auto color = Color::index(Color::Cpc::YELLOW);

        // FPS
        const std::string FPS_TEXT = std::to_string(fps_.last_value) + " FPS";
        text->writeColored(Options::game.width - text->length(FPS_TEXT), 0, FPS_TEXT, color);
    }
}

// Limpia la game_surface_
void Screen::clearSurface(Uint8 index) { game_surface_->clear(index); }

// Establece el tamaño del borde
void Screen::setBorderWidth(int width) { Options::video.border.width = width; }

// Establece el tamaño del borde
void Screen::setBorderHeight(int height) { Options::video.border.height = height; }

// Establece si se ha de ver el borde en el modo ventana
void Screen::setBorderEnabled(bool value) { Options::video.border.enabled = value; }

// Muestra la ventana
void Screen::show() { SDL_ShowWindow(window_); }

// Oculta la ventana
void Screen::hide() { SDL_HideWindow(window_); }

// Establece la visibilidad de las notificaciones
void Screen::setNotificationsEnabled(bool value) { notifications_enabled_ = value; }

// Activa / desactiva la información de debug
void Screen::toggleDebugInfo() { show_debug_info_ = !show_debug_info_; }

// Alterna entre activar y desactivar el escalado entero
void Screen::toggleIntegerScale() {
    Options::video.integer_scale = !Options::video.integer_scale;
    SDL_SetRenderLogicalPresentation(renderer_, Options::game.width, Options::game.height, Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
}

// Alterna entre activar y desactivar el V-Sync
void Screen::toggleVSync() {
    Options::video.vertical_sync = !Options::video.vertical_sync;
    SDL_SetRenderVSync(renderer_, Options::video.vertical_sync ? 1 : SDL_RENDERER_VSYNC_DISABLED);
}

// Getters
auto Screen::getRenderer() -> SDL_Renderer* { return renderer_; }
auto Screen::getRendererSurface() -> std::shared_ptr<Surface> { return (*renderer_surface_); }
auto Screen::getBorderSurface() -> std::shared_ptr<Surface> { return border_surface_; }

auto loadData(const std::string& filepath) -> std::vector<uint8_t> {
    // Load using ResourceHelper (supports both filesystem and pack)
    return Resource::Helper::loadFile(filepath);
}

// Carga el contenido de los archivos GLSL
void Screen::loadShaders() {
    if (vertex_shader_source_.empty()) {
        // Detectar si necesitamos OpenGL ES (Raspberry Pi)
        // Intentar cargar versión ES primero si existe
        std::string vertex_file = "crtpi_vertex_es.glsl";
        auto data = loadData(Resource::List::get()->get(vertex_file));

        if (data.empty()) {
            // Si no existe versión ES, usar versión Desktop
            vertex_file = "crtpi_vertex.glsl";
            data = loadData(Resource::List::get()->get(vertex_file));
            std::cout << "Usando shaders OpenGL Desktop 3.3\n";
        } else {
            std::cout << "Usando shaders OpenGL ES 3.0 (Raspberry Pi)\n";
        }

        if (!data.empty()) {
            vertex_shader_source_ = std::string(data.begin(), data.end());
        }
    }
    if (fragment_shader_source_.empty()) {
        // Intentar cargar versión ES primero si existe
        std::string fragment_file = "crtpi_fragment_es.glsl";
        auto data = loadData(Resource::List::get()->get(fragment_file));

        if (data.empty()) {
            // Si no existe versión ES, usar versión Desktop
            fragment_file = "crtpi_fragment.glsl";
            data = loadData(Resource::List::get()->get(fragment_file));
        }

        if (!data.empty()) {
            fragment_shader_source_ = std::string(data.begin(), data.end());
        }
    }
}

// Inicializa los shaders
void Screen::initShaders() {
#ifndef __APPLE__
    if (Options::video.shaders) {
        loadShaders();
        if (!shader_backend_) {
            shader_backend_ = std::make_unique<Rendering::OpenGLShader>();
        }
        shader_backend_->init(window_, Options::video.border.enabled ? border_texture_ : game_texture_, vertex_shader_source_, fragment_shader_source_);
        // shader_backend_->init(window_, shaders_texture_, vertex_shader_source_, fragment_shader_source_);
    }
#else
    // En macOS, OpenGL está deprecated y rinde mal
    // TODO: Implementar backend de Metal para shaders en macOS
    std::cout << "WARNING: Shaders no disponibles en macOS (OpenGL deprecated). Usa Metal backend.\n";
#endif
}

// Obtiene información sobre la pantalla
void Screen::getDisplayInfo() {
    std::cout << "\n** VIDEO SYSTEM **\n";

    int num_displays = 0;
    SDL_DisplayID* displays = SDL_GetDisplays(&num_displays);
    if (displays != nullptr) {
        for (int i = 0; i < num_displays; ++i) {
            SDL_DisplayID instance_id = displays[i];
            const char* name = SDL_GetDisplayName(instance_id);

            std::cout << "Display " << instance_id << ": " << ((name != nullptr) ? name : "Unknown") << '\n';
        }

        const auto* dm = SDL_GetCurrentDisplayMode(displays[0]);

        // Guarda información del monitor en display_monitor_
        const char* first_display_name = SDL_GetDisplayName(displays[0]);
        display_monitor_.name = (first_display_name != nullptr) ? first_display_name : "Unknown";
        display_monitor_.width = static_cast<int>(dm->w);
        display_monitor_.height = static_cast<int>(dm->h);
        display_monitor_.refresh_rate = static_cast<int>(dm->refresh_rate);

        // Calcula el máximo factor de zoom que se puede aplicar a la pantalla
        Options::window.max_zoom = std::min(dm->w / Options::game.width, dm->h / Options::game.height);
        Options::window.zoom = std::min(Options::window.zoom, Options::window.max_zoom);

        // Muestra información sobre el tamaño de la pantalla y de la ventana de juego
        std::cout << "Current display mode: " << static_cast<int>(dm->w) << "x" << static_cast<int>(dm->h) << " @ " << static_cast<int>(dm->refresh_rate) << "Hz\n";

        std::cout << "Window resolution: " << static_cast<int>(Options::game.width) << "x" << static_cast<int>(Options::game.height) << " x" << Options::window.zoom << '\n';

        Options::video.info = std::to_string(static_cast<int>(dm->w)) + "x" +
            std::to_string(static_cast<int>(dm->h)) + " @ " +
            std::to_string(static_cast<int>(dm->refresh_rate)) + " Hz";

        // Calcula el máximo factor de zoom que se puede aplicar a la pantalla
        const int MAX_ZOOM = std::min(dm->w / Options::game.width, (dm->h - WINDOWS_DECORATIONS) / Options::game.height);

        // Normaliza los valores de zoom
        Options::window.zoom = std::min(Options::window.zoom, MAX_ZOOM);

        SDL_free(displays);
    }
}

// Arranca SDL VIDEO y crea la ventana
auto Screen::initSDLVideo() -> bool {
    // Inicializar SDL
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        std::cerr << "FATAL: Failed to initialize SDL_VIDEO! SDL Error: " << SDL_GetError() << '\n';
        return false;
    }

    // Obtener información de la pantalla
    getDisplayInfo();

    // Configurar hint para renderizado
#ifdef __APPLE__
    if (!SDL_SetHint(SDL_HINT_RENDER_DRIVER, "metal")) {
        std::cout << "WARNING: Failed to set Metal hint!\n";
    }
#else
    // Configurar hint de render driver
    if (!SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl")) {
        std::cout << "WARNING: Failed to set OpenGL hint!\n";
    }

#ifdef _WIN32
    // Windows: Pedir explícitamente OpenGL 3.3 Core Profile
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    std::cout << "Solicitando OpenGL 3.3 Core Profile\n";
#else
    // Linux: Dejar que SDL elija (Desktop 3.3 en PC, ES 3.0 en RPi automáticamente)
    std::cout << "Usando OpenGL por defecto del sistema\n";
#endif
#endif

    // Crear ventana
    const auto WINDOW_WIDTH = Options::video.border.enabled ? Options::game.width + (Options::video.border.width * 2) : Options::game.width;
    const auto WINDOW_HEIGHT = Options::video.border.enabled ? Options::game.height + (Options::video.border.height * 2) : Options::game.height;
#ifdef __APPLE__
    SDL_WindowFlags window_flags = SDL_WINDOW_METAL;
#else
    SDL_WindowFlags window_flags = SDL_WINDOW_OPENGL;
#endif
    if (Options::video.fullscreen) {
        window_flags |= SDL_WINDOW_FULLSCREEN;
    }
    window_ = SDL_CreateWindow(Options::window.caption.c_str(), WINDOW_WIDTH * Options::window.zoom, WINDOW_HEIGHT * Options::window.zoom, window_flags);

    if (window_ == nullptr) {
        std::cerr << "FATAL: Failed to create window! SDL Error: " << SDL_GetError() << '\n';
        SDL_Quit();
        return false;
    }

    // Crear renderer
    renderer_ = SDL_CreateRenderer(window_, nullptr);
    if (renderer_ == nullptr) {
        std::cerr << "FATAL: Failed to create renderer! SDL Error: " << SDL_GetError() << '\n';
        SDL_DestroyWindow(window_);
        window_ = nullptr;
        SDL_Quit();
        return false;
    }

    // Configurar renderer
    const int EXTRA_WIDTH = Options::video.border.enabled ? Options::video.border.width * 2 : 0;
    const int EXTRA_HEIGHT = Options::video.border.enabled ? Options::video.border.height * 2 : 0;
    SDL_SetRenderLogicalPresentation(
        renderer_,
        Options::game.width + EXTRA_WIDTH,
        Options::game.height + EXTRA_HEIGHT,
        Options::video.integer_scale ? SDL_LOGICAL_PRESENTATION_INTEGER_SCALE : SDL_LOGICAL_PRESENTATION_LETTERBOX);
    SDL_SetRenderDrawColor(renderer_, 0x00, 0x00, 0x00, 0xFF);
    SDL_SetRenderDrawBlendMode(renderer_, SDL_BLENDMODE_BLEND);
    SDL_SetRenderVSync(renderer_, Options::video.vertical_sync ? 1 : SDL_RENDERER_VSYNC_DISABLED);

    std::cout << "Video system initialized successfully\n";
    return true;
}

// Crea el objeto de texto
void Screen::createText() {
    // Carga la surface de la fuente directamente del archivo
    auto surface = std::make_shared<Surface>(Resource::List::get()->get("aseprite.gif"));

    // Crea el objeto de texto (el constructor de Text carga el archivo text_file internamente)
    text_ = std::make_shared<Text>(surface, Resource::List::get()->get("aseprite.txt"));
}